name: Run libc unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install ninja-build, python
      run: sudo apt-get install ninja-build python-is-python3 python3-pip
    - name: Install meson
      run: python -m pip install --user meson
    - uses: actions/checkout@v2
    - name: Create build directory
      run: meson setup build --native-file=native-files/libc-local.ini
    - name: Build and test
      run: cd build && ninja test
